login: &login
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: ranker
  password: 9Q&8nc4dBjJH*22Cae9@Np%96
  min_messages: warning
  
# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  database: ranker_development
  <<: *login

test: &test
  database: ranker_test
  <<: *login

production:
  database: ranker_production
  <<: *login

cucumber:
  <<: *test